/**
 * Manages preview tokens that map random IDs to localhost ports, enabling
 * token-gated reverse proxying of agent-started dev servers.
 *
 * Responsibilities:
 * - Maintains an in-memory token store (Map on globalThis for hot-reload persistence)
 * - Rewrites agent output: replaces localhost URLs with preview URLs
 * - Rewrites user input: replaces preview URLs back to localhost URLs
 * - Cleans up tokens when sessions are closed
 */

// ============================================================================
// CONSTANTS
// ============================================================================

/**
 * Matches localhost-style URLs with a 4-5 digit port and an optional path.
 * Captures: group 1 = port, group 2 = path (including leading slash) or undefined.
 */
const LOCALHOST_URL_REGEX =
  /(?:https?:\/\/)?(?:localhost|127\.0\.0\.1|0\.0\.0\.0):(\d{4,5})(\/[^\s)"'>]*)?/g;

/**
 * Matches preview URLs generated by this module.
 * Captures: group 1 = token, group 2 = path (including leading slash) or undefined.
 */
const PREVIEW_URL_REGEX = /\/preview\/([a-f0-9-]{36})(\/[^\s)"'>]*)?/g;

// ============================================================================
// TYPES
// ============================================================================

export interface PreviewToken {
  token: string;
  port: number;
  sessionId: string;
  createdAt: Date;
}

// ============================================================================
// TOKEN STORE
// ============================================================================

/** Persist across Next.js hot-reloads in dev by attaching to globalThis. */
const globalTokens = globalThis as unknown as {
  __phonecc_preview_tokens?: Map<string, PreviewToken>;
};
if (!globalTokens.__phonecc_preview_tokens) {
  globalTokens.__phonecc_preview_tokens = new Map<string, PreviewToken>();
}
const tokenStore = globalTokens.__phonecc_preview_tokens;

// ============================================================================
// MAIN FUNCTIONS
// ============================================================================

/**
 * Finds localhost URLs in text, creates tokens for new session+port pairs
 * (reuses existing tokens for the same pair), and replaces with preview URLs.
 *
 * @param sessionId - The session that produced this text
 * @param text - Agent output that may contain localhost URLs
 * @returns The text with localhost URLs replaced by preview URLs
 */
export function rewriteAgentOutput(sessionId: string, text: string): string {
  console.log("[rewriteAgentOutput] sessionId:", sessionId, "text length:", text.length);
  console.log("[rewriteAgentOutput] text snippet:", text.slice(0, 200));
  const matches = text.match(LOCALHOST_URL_REGEX);
  console.log("[rewriteAgentOutput] localhost matches:", matches);
  const result = text.replace(LOCALHOST_URL_REGEX, (_match, portStr: string, pathPart?: string) => {
    const port = parseInt(portStr, 10);
    const token = getOrCreateToken(sessionId, port);
    const urlPath = pathPart ?? "";
    const replacement = `/preview/${token.token}${urlPath}`;
    console.log("[rewriteAgentOutput] replacing:", _match, "→", replacement);
    return replacement;
  });
  console.log("[rewriteAgentOutput] result snippet:", result.slice(0, 200));
  return result;
}

/**
 * Finds preview URLs in text and replaces them with the original localhost URL.
 * Unknown tokens are left as-is.
 *
 * @param text - User input that may contain preview URLs
 * @returns The text with preview URLs replaced by localhost URLs
 */
export function rewriteUserInput(text: string): string {
  return text.replace(PREVIEW_URL_REGEX, (match, tokenStr: string, pathPart?: string) => {
    const entry = tokenStore.get(tokenStr);
    if (!entry) return match;
    const urlPath = pathPart ?? "";
    return `http://localhost:${entry.port}${urlPath}`;
  });
}

/**
 * Returns the token entry for a given token string. Used by the proxy route
 * to look up which port to forward to.
 *
 * @param token - The UUID token string
 * @returns The PreviewToken entry, or undefined if not found
 */
export function lookupToken(token: string): PreviewToken | undefined {
  return tokenStore.get(token);
}

/**
 * Removes all tokens belonging to a session. Called when a session is closed.
 *
 * @param sessionId - The session whose tokens should be removed
 */
export function cleanupSession(sessionId: string): void {
  for (const [key, entry] of tokenStore) {
    if (entry.sessionId === sessionId) {
      tokenStore.delete(key);
    }
  }
}

// ============================================================================
// HELPER FUNCTIONS
// ============================================================================

/**
 * Returns an existing token for the session+port pair, or creates a new one.
 *
 * @param sessionId - The session ID
 * @param port - The localhost port number
 * @returns The existing or newly created PreviewToken
 */
function getOrCreateToken(sessionId: string, port: number): PreviewToken {
  // Check for existing token with same session+port
  for (const entry of tokenStore.values()) {
    if (entry.sessionId === sessionId && entry.port === port) {
      return entry;
    }
  }

  // Create new token
  const token: PreviewToken = {
    token: crypto.randomUUID(),
    port,
    sessionId,
    createdAt: new Date(),
  };
  tokenStore.set(token.token, token);
  return token;
}
